import { config, fields, collection, singleton } from '@keystatic/core';

export default config({
  storage: {
    kind: 'github',
    repo: { owner: 'NaagAlgates', name: 'ssvk-brisbane' },
  },
  ui: {
    brand: { name: 'SSVK Brisbane' },
    navigation: {
      'Site & Pages': ['siteConfig', 'aboutPage', 'donation'],
      'Schedule': ['openingHours', 'canteenStatus'],
      'Events & Services': ['events', 'festivals', 'poojaServices'],
      'Canteen Menu': ['canteenMenu'],
      'People': ['committee'],
      'Updates': ['notices', 'newsletters'],
      'Library': ['libraryDocuments'],
    },
  },
  singletons: {
    siteConfig: singleton({
      label: 'Site Configuration',
      path: 'src/content/site-config/',
      schema: {
        templeAddressLine1: fields.text({ label: 'Address line 1', validation: { isRequired: true } }),
        templeAddressLine2: fields.text({ label: 'Address line 2' }),
        suburb: fields.text({ label: 'Suburb', validation: { isRequired: true } }),
        postcode: fields.text({ label: 'Postcode', validation: { isRequired: true } }),
        state: fields.text({ label: 'State', defaultValue: 'QLD' }),
        country: fields.text({ label: 'Country', defaultValue: 'Australia' }),
        postalAddress: fields.text({ label: 'Postal address (if different)' }),
        phonePrimary: fields.text({ label: 'Primary phone', validation: { isRequired: true } }),
        emailGeneral: fields.text({ label: 'General email', validation: { isRequired: true } }),
        googleMapsUrl: fields.url({ label: 'Google Maps link', validation: { isRequired: true } }),
        googleMapsEmbedUrl: fields.url({ label: 'Google Maps embed iframe src' }),
        facebookUrl: fields.url({ label: 'Facebook page' }),
        youtubeUrl: fields.url({ label: 'YouTube channel' }),
      },
    }),
    aboutPage: singleton({
      label: 'About Page Content',
      path: 'src/content/about/',
      schema: {
        historyIntro: fields.markdoc({ label: 'History intro' }),
        historyBody: fields.markdoc({ label: 'History body' }),
        vinayakarIntro: fields.markdoc({ label: 'Lord Vinayakar intro' }),
        vinayakarBody: fields.markdoc({ label: 'Lord Vinayakar (extended)' }),
        generalAbout: fields.markdoc({ label: 'General about content' }),
      },
    }),
    donation: singleton({
      label: 'Donation Details',
      path: 'src/content/donation/',
      schema: {
        bankName: fields.text({ label: 'Bank name', validation: { isRequired: true } }),
        accountName: fields.text({ label: 'Account name', validation: { isRequired: true } }),
        bsb: fields.text({ label: 'BSB (NNN-NNN)', validation: { isRequired: true } }),
        accountNumber: fields.text({ label: 'Account number', validation: { isRequired: true } }),
        payid: fields.text({ label: 'PayID (optional)' }),
        referenceInstructions: fields.markdoc({ label: 'Reference instructions' }),
        dgrStatusNote: fields.markdoc({ label: 'DGR / tax status note' }),
        treasurerEmail: fields.text({ label: 'Treasurer email (for receipts)', validation: { isRequired: true } }),
      },
    }),
    openingHours: singleton({
      label: 'Opening Hours',
      path: 'src/content/opening-hours/',
      schema: {
        weekdayMorningOpen: fields.text({ label: 'Mon–Fri morning open', defaultValue: '7:30am' }),
        weekdayMorningClose: fields.text({ label: 'Mon–Fri morning close', defaultValue: '12:00pm' }),
        weekdayEveningOpen: fields.text({ label: 'Mon–Fri evening open', defaultValue: '5:00pm' }),
        weekdayEveningClose: fields.text({ label: 'Mon–Fri evening close', defaultValue: '8:30pm' }),
        weekendMorningOpen: fields.text({ label: 'Sat–Sun morning open', defaultValue: '7:30am' }),
        weekendMorningClose: fields.text({ label: 'Sat–Sun morning close', defaultValue: '1:00pm' }),
        weekendEveningOpen: fields.text({ label: 'Sat–Sun evening open', defaultValue: '5:00pm' }),
        weekendEveningClose: fields.text({ label: 'Sat–Sun evening close', defaultValue: '8:30pm' }),
        poojaMorning: fields.text({ label: 'Morning pooja time', defaultValue: '9:00am – 9:30am' }),
        poojaEvening: fields.text({ label: 'Evening pooja time', defaultValue: '7:00pm – 7:30pm' }),
        specialNotice: fields.markdoc({ label: 'Special hours notice (festivals etc.)' }),
      },
    }),
    canteenStatus: singleton({
      label: 'Canteen Status (live toggle)',
      path: 'src/content/canteen-status/',
      schema: {
        mode: fields.select({
          label: 'Status mode',
          description: 'Auto: open weekends 9am-2pm, closed weekdays. Force open/closed overrides for a specific day.',
          options: [
            { label: 'Auto (open weekends only)', value: 'auto' },
            { label: 'Force open today', value: 'force_open' },
            { label: 'Force closed today', value: 'force_closed' },
          ],
          defaultValue: 'auto',
        }),
        weekendOpenTime: fields.text({ label: 'Default weekend open time', defaultValue: '9:00am' }),
        weekendCloseTime: fields.text({ label: 'Default weekend close time', defaultValue: '2:00pm' }),
        overrideOpenTime: fields.text({ label: 'Override open time (used when forced open)', defaultValue: '9:00am' }),
        overrideCloseTime: fields.text({ label: 'Override close time (used when forced open)', defaultValue: '2:00pm' }),
        specialNotice: fields.text({ label: 'Special notice (optional)' }),
      },
    }),
  },
  collections: {
    events: collection({
      label: 'Events',
      slugField: 'title',
      path: 'src/content/events/*',
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        titleTamil: fields.text({ label: 'Title (Tamil)' }),
        date: fields.date({ label: 'Date', validation: { isRequired: true } }),
        startTime: fields.text({ label: 'Start time' }),
        endTime: fields.text({ label: 'End time' }),
        recurring: fields.checkbox({ label: 'Recurring event' }),
        description: fields.markdoc({ label: 'Description' }),
        locationWithinTemple: fields.text({ label: 'Location within temple' }),
        photo: fields.image({ label: 'Photo', directory: 'public/images/events', publicPath: '/images/events/' }),
      },
    }),
    festivals: collection({
      label: 'Festival Calendar',
      slugField: 'name',
      path: 'src/content/festivals/*',
      schema: {
        name: fields.slug({ name: { label: 'Name (English)', validation: { isRequired: true } } }),
        nameTamil: fields.text({ label: 'Name (Tamil)', validation: { isRequired: true } }),
        date: fields.date({ label: 'Date', validation: { isRequired: true } }),
        time: fields.text({ label: 'Time' }),
        type: fields.select({
          label: 'Type',
          options: [
            { label: 'Major', value: 'major' },
            { label: 'Minor', value: 'minor' },
          ],
          defaultValue: 'minor',
        }),
        description: fields.markdoc({ label: 'Description' }),
      },
    }),
    poojaServices: collection({
      label: 'Pooja & Services',
      slugField: 'name',
      path: 'src/content/pooja-services/*',
      schema: {
        name: fields.slug({ name: { label: 'Name (English)', validation: { isRequired: true } } }),
        nameTamil: fields.text({ label: 'Name (Tamil)', validation: { isRequired: true } }),
        durationMinutes: fields.integer({ label: 'Duration (minutes)' }),
        priceAud: fields.number({ label: 'Price (AUD)', validation: { isRequired: true, min: 0 } }),
        description: fields.markdoc({ label: 'Description' }),
        prerequisites: fields.markdoc({ label: 'Prerequisites' }),
      },
    }),
    canteenMenu: collection({
      label: 'Canteen Menu Items',
      slugField: 'name',
      path: 'src/content/canteen-menu/*',
      schema: {
        name: fields.slug({ name: { label: 'Item name', validation: { isRequired: true } } }),
        nameTamil: fields.text({ label: 'Name (Tamil)' }),
        price: fields.number({ label: 'Price (AUD)', validation: { isRequired: true, min: 0 } }),
        category: fields.select({
          label: 'Category',
          options: [
            { label: 'Breakfast', value: 'breakfast' },
            { label: 'Lunch', value: 'lunch' },
            { label: 'Snacks', value: 'snacks' },
            { label: 'Drinks', value: 'drinks' },
            { label: 'Prasadam', value: 'prasadam' },
          ],
          defaultValue: 'snacks',
        }),
        dietary: fields.multiselect({
          label: 'Dietary',
          options: [
            { label: 'Vegetarian', value: 'veg' },
            { label: 'Vegan', value: 'vegan' },
            { label: 'Jain', value: 'jain' },
          ],
          defaultValues: ['veg'],
        }),
        description: fields.text({ label: 'Description' }),
        photo: fields.image({ label: 'Photo', directory: 'public/images/menu', publicPath: '/images/menu/' }),
        available: fields.checkbox({ label: 'Available now', defaultValue: true }),
      },
    }),
    notices: collection({
      label: 'Notices',
      slugField: 'title',
      path: 'src/content/notices/*',
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        datePosted: fields.date({ label: 'Date posted', validation: { isRequired: true } }),
        body: fields.markdoc({ label: 'Body' }),
        expiresOn: fields.date({ label: 'Expires on (auto-hide after this date)' }),
        priority: fields.select({
          label: 'Priority',
          options: [
            { label: 'High', value: 'high' },
            { label: 'Normal', value: 'normal' },
            { label: 'Low', value: 'low' },
          ],
          defaultValue: 'normal',
        }),
      },
    }),
    newsletters: collection({
      label: 'Newsletters',
      slugField: 'title',
      path: 'src/content/newsletters/*',
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        date: fields.date({ label: 'Issue date', validation: { isRequired: true } }),
        body: fields.markdoc({ label: 'Body' }),
        coverImage: fields.image({ label: 'Cover image', directory: 'public/images/newsletters', publicPath: '/images/newsletters/' }),
        pdfUrl: fields.text({ label: 'PDF download URL (e.g. /documents/newsletters/x.pdf)' }),
      },
    }),
    libraryDocuments: collection({
      label: 'Library Documents',
      slugField: 'title',
      path: 'src/content/library-documents/*',
      schema: {
        title: fields.slug({ name: { label: 'Title', validation: { isRequired: true } } }),
        category: fields.select({
          label: 'Category',
          options: [
            { label: 'Koyil Mani Magazine', value: 'koyil-mani' },
            { label: 'Temple Worship Series', value: 'worship-series' },
          ],
          defaultValue: 'koyil-mani',
        }),
        date: fields.date({ label: 'Date / Issue date (optional)' }),
        pdfUrl: fields.text({ label: 'PDF path (e.g. /documents/worship-series/x.pdf)', validation: { isRequired: true } }),
        description: fields.text({ label: 'One-line description (optional)' }),
        sortOrder: fields.integer({ label: 'Sort order (Koyil Mani: issue number; Worship Series: guide number)', defaultValue: 0 }),
      },
    }),
    committee: collection({
      label: 'Committee Members',
      slugField: 'name',
      path: 'src/content/committee/*',
      schema: {
        name: fields.slug({ name: { label: 'Name', validation: { isRequired: true } } }),
        nameTamil: fields.text({ label: 'Name (Tamil)' }),
        role: fields.text({ label: 'Role', validation: { isRequired: true } }),
        roleTamil: fields.text({ label: 'Role (Tamil)' }),
        photo: fields.image({ label: 'Photo', directory: 'public/images/committee', publicPath: '/images/committee/' }),
        contactEmail: fields.text({ label: 'Contact email (optional)' }),
        sortOrder: fields.integer({ label: 'Sort order', defaultValue: 0 }),
        termStartYear: fields.integer({ label: 'Term start year' }),
        isCurrent: fields.checkbox({ label: 'Currently serving', defaultValue: true }),
      },
    }),
  },
});
